# Generated by Django 5.1.5 on 2026-03-16 14:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def assign_existing_table_owners(apps, schema_editor):
    user_app_label, user_model_name = settings.AUTH_USER_MODEL.split(".")
    User = apps.get_model(user_app_label, user_model_name)
    DataTable = apps.get_model("accessforge", "DataTable")
    TableMembership = apps.get_model("accessforge", "TableMembership")

    fallback_owner = User.objects.filter(is_superuser=True).order_by("id").first()
    if fallback_owner is None:
        fallback_owner = User.objects.order_by("id").first()
    if fallback_owner is None:
        return

    for table in DataTable.objects.filter(owner__isnull=True):
        table.owner_id = fallback_owner.pk
        table.save(update_fields=["owner"])

    for table in DataTable.objects.exclude(owner__isnull=True):
        TableMembership.objects.get_or_create(
            table_id=table.pk,
            user_id=table.owner_id,
            defaults={"role": "owner"},
        )


class Migration(migrations.Migration):

    dependencies = [
        ('accessforge', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='related_table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incoming_relations', to='accessforge.datatable'),
        ),
        migrations.AddField(
            model_name='datatable',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_access_tables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='datatable',
            name='record_label_field_slug',
            field=models.SlugField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('long_text', 'Long text'), ('integer', 'Integer'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('date', 'Date'), ('datetime', 'Date and time'), ('email', 'Email'), ('url', 'URL'), ('relation', 'Related record')], default='text', max_length=20),
        ),
        migrations.CreateModel(
            name='FormLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Data entry form', max_length=120)),
                ('description', models.TextField(blank=True)),
                ('columns', models.PositiveSmallIntegerField(default=2)),
                ('submit_label', models.CharField(default='Save record', max_length=80)),
                ('table', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='form_layout', to='accessforge.datatable')),
            ],
            options={
                'ordering': ('table__name',),
            },
        ),
        migrations.CreateModel(
            name='FormLayoutField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('visible', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('section', models.CharField(blank=True, max_length=120)),
                ('label_override', models.CharField(blank=True, max_length=120)),
                ('help_override', models.CharField(blank=True, max_length=255)),
                ('column_span', models.PositiveSmallIntegerField(default=1)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='layout_items', to='accessforge.datafield')),
                ('layout', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accessforge.formlayout')),
            ],
            options={
                'ordering': ('order', 'id'),
                'constraints': [models.UniqueConstraint(fields=('layout', 'field'), name='unique_layout_field_item')],
            },
        ),
        migrations.CreateModel(
            name='SavedQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True)),
                ('match_mode', models.CharField(choices=[('all', 'Match all rules'), ('any', 'Match any rule')], default='all', max_length=20)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('is_shared', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saved_queries', to=settings.AUTH_USER_MODEL)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_queries', to='accessforge.datatable')),
            ],
            options={
                'ordering': ('table__name', 'name'),
                'constraints': [models.UniqueConstraint(fields=('table', 'name'), name='unique_saved_query_name_per_table')],
            },
        ),
        migrations.CreateModel(
            name='TableMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], default='viewer', max_length=20)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='accessforge.datatable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('table__name', 'user__username'),
                'constraints': [models.UniqueConstraint(fields=('table', 'user'), name='unique_table_user_membership')],
            },
        ),
        migrations.RunPython(assign_existing_table_owners, migrations.RunPython.noop),
    ]
