# Generated by Django 5.1.5 on 2026-03-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessforge', '0002_datafield_related_table_datatable_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='datafield',
            name='edit_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], default='editor', max_length=20),
        ),
        migrations.AddField(
            model_name='datafield',
            name='view_role',
            field=models.CharField(choices=[('viewer', 'Viewer'), ('editor', 'Editor'), ('owner', 'Owner')], default='viewer', max_length=20),
        ),
    ]
