# Generated by Django 5.1.5 on 2026-03-16 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accessforge', '0003_datafield_edit_role_datafield_view_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datafield',
            name='edit_role',
            field=models.CharField(choices=[('viewer', '檢視者'), ('editor', '編輯者'), ('owner', '擁有者')], default='editor', max_length=20),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='field_type',
            field=models.CharField(choices=[('text', '文字'), ('long_text', '長文字'), ('integer', '整數'), ('decimal', '小數'), ('boolean', '布林'), ('date', '日期'), ('datetime', '日期時間'), ('email', '電子郵件'), ('url', '網址'), ('relation', '關聯記錄')], default='text', max_length=20),
        ),
        migrations.AlterField(
            model_name='datafield',
            name='view_role',
            field=models.CharField(choices=[('viewer', '檢視者'), ('editor', '編輯者'), ('owner', '擁有者')], default='viewer', max_length=20),
        ),
        migrations.AlterField(
            model_name='formlayout',
            name='submit_label',
            field=models.CharField(default='儲存資料', max_length=80),
        ),
        migrations.AlterField(
            model_name='formlayout',
            name='title',
            field=models.CharField(default='資料輸入表單', max_length=120),
        ),
        migrations.AlterField(
            model_name='savedquery',
            name='match_mode',
            field=models.CharField(choices=[('all', '符合全部條件'), ('any', '符合任一條件')], default='all', max_length=20),
        ),
        migrations.AlterField(
            model_name='tablemembership',
            name='role',
            field=models.CharField(choices=[('viewer', '檢視者'), ('editor', '編輯者'), ('owner', '擁有者')], default='viewer', max_length=20),
        ),
    ]
